trigger:
  branches:
    include: [sloria, test-me-*]
  tags:
    include: ['*']

jobs:
- template: job--pre-commit.yml
- template: job--python-tox.yml
  parameters:
    coverage: false
    toxenvs: [py27, py35, py36, py37, py38, py39, pypy, pypy3, docs]
